import { selectOption } from "./select";
import { test, expect } from '@playwright/test';
import { startTest } from './prepared';

test('normal mode archives, searches, filters, restores and confirms red permanent deletion', async ({page, request}) => {
  const label = `Archive lifecycle ${Date.now()}`;
  const workspace = await (await request.post('/api/workspaces', {data: {name: label}})).json();
  const create = async (title: string) => (await (await request.post(`/api/workspaces/${workspace.id}/meetings`, {data: {title}})).json()).meeting;
  const one = await create('Discovery notes');
  await create('Operations draft');
  await request.post(`/api/meetings/${one.id}/notes`, {data: {body: 'Preserve this note'}});
  await request.put('/api/settings/test-mode', {data: {enabled: false}});
  await page.goto('/');
  await selectOption(page.getByLabel('Workspace', {exact: true}), workspace.id);
  await page.getByRole('button', {name: 'Workspace actions', exact: true}).click();
  await page.getByRole('button', {name: 'Archive all meetings', exact: true}).click();
  await expect(page.getByRole('dialog')).toContainText('You can restore them');
  await page.getByRole('button', {name: 'Archive meetings', exact: true}).click();
  await expect(page.getByRole('navigation', {name: 'Meetings', exact: true}).getByRole('button')).toHaveCount(0);
  await expect(page.getByRole('heading', {name: label})).toBeVisible();
  expect((await (await request.get(`/api/meetings/${one.id}`)).json()).notes[0].body).toBe('Preserve this note');
  await page.getByRole('button', {name: 'Archives', exact: true}).click();
  await selectOption(page.getByLabel('Workspace filter'), workspace.id);
  await selectOption(page.getByLabel('Meeting type'), 'real');
  await expect(page.getByText('No archived meetings match.')).toBeVisible();
  await selectOption(page.getByLabel('Meeting type'), 'draft');
  await page.getByLabel('Search archives').fill('Discovery');
  await expect(page.locator('.ex-archive-list article')).toHaveCount(1);
  const remove = page.getByRole('button', {name: 'Delete permanently', exact: true});
  const color = await remove.evaluate(el => getComputedStyle(el).color);
  expect(color).toBe('rgb(173, 52, 68)');
  await remove.click();
  await expect(page.getByRole('dialog')).toContainText('protected transcript archive is retained');
  await expect(page.getByRole('button', {name: 'Cancel', exact: true})).toBeFocused();
  await page.keyboard.press('Escape');
  expect((await request.get(`/api/meetings/${one.id}`)).status()).toBe(200);
  await remove.click();
  await page.getByRole('button', {name: 'Delete meeting', exact: true}).click();
  await expect(page.locator('.ex-archive-list article')).toHaveCount(0);
  expect((await request.get(`/api/meetings/${one.id}`)).status()).toBe(404);
  await page.getByLabel('Search archives').fill('');
  await page.getByRole('button', {name: 'Restore meeting', exact: true}).click();
  await expect(page.getByRole('navigation', {name: 'Meetings', exact: true}).getByText('Operations draft')).toBeVisible();
  await page.getByRole('button', {name: 'Workspace actions', exact: true}).click();
  await page.getByRole('button', {name: 'Archive workspace', exact: true}).click();
  await page.getByRole('dialog').getByRole('button', {name: 'Archive workspace', exact: true}).click();
  await page.getByRole('combobox', {name:'Workspace',exact:true}).click();
  await expect(page.getByRole('listbox')).toBeVisible();
  await expect(page.getByRole('option', {name:label,exact:true})).toHaveCount(0);
  await page.keyboard.press('Escape');
  await page.getByRole('button', {name: 'Archives', exact: true}).click();
  await page.getByRole('button', {name: 'Workspaces', exact: true}).click();
  await page.getByLabel('Search archives').fill(label);
  await page.setViewportSize({width: 760, height: 900});
  await page.screenshot({path: '/tmp/explore-archives-narrow.png', fullPage: true});
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBeTruthy();
  await page.getByRole('button', {name: 'Restore workspace', exact: true}).click();
  await page.getByRole('combobox', {name:'Workspace',exact:true}).click();
  await expect(page.getByRole('listbox')).toBeVisible();
  await expect(page.getByRole('option', {name:label,exact:true})).toHaveCount(1);
  await page.keyboard.press('Escape');
});

test('spoken questions stay separate from suggestions and expose original evidence', async ({page, request}) => {
  const w = await (await request.post('/api/workspaces', {data: {name: 'Spoken question review'}})).json();
  const draft = await (await request.post(`/api/workspaces/${w.id}/meetings`, {data: {title: 'Manual questions'}})).json();
  const detail = await startTest(request, draft.meeting.id);
  await request.patch(`/api/meetings/${draft.meeting.id}/preferences`, {data: {revision: detail.meeting.context_version, question_interval: 0}});
  await page.goto('/');
  await selectOption(page.getByLabel('Workspace', {exact: true}), w.id);
  const event = {event_id: 'manual-question', segment_id: 'manual', revision: 1, text: 'What happened during the last approval?', is_final: true, speaker_id: 'cofounder', speaker_name: 'Alex Test', start_ms: 0, end_ms: 5000};
  await request.post(`/api/sessions/${detail.session.id}/inject`, {data: event});
  const panel = page.locator('.ex-spoken-questions');
  await expect(panel.locator('summary')).toContainText('1 detected');
  await panel.locator('summary').click();
  await expect(panel.getByText(event.text, {exact: true})).toBeVisible();
  await expect(panel.getByText(/Unconfirmed speaker/)).toBeVisible();
  await expect(page.locator('.ex-question')).toHaveCount(0);
  await panel.getByRole('button', {name: /View source/}).click();
  await expect(page.locator('.ex-transcript-list span.highlight')).toHaveCount(1);
  await selectOption(panel.getByLabel('Speaker role'), 'interviewer');
  await expect(panel.getByText('No detected questions in this view.')).toBeVisible();
  await selectOption(panel.getByLabel('Speaker role'), '');
  await request.post(`/api/sessions/${detail.session.id}/inject`, {data: {...event, event_id: 'correction', revision: 2, text: 'What failed during the last approval?'}});
  await expect(panel.getByText('What failed during the last approval?', {exact: true})).toBeVisible();
  await expect(panel.getByText(event.text, {exact: true})).toHaveCount(0);
  await panel.getByLabel('Include earlier revisions').check();
  await expect(panel.getByText(event.text, {exact: true})).toBeVisible();
  await page.screenshot({path: '/tmp/explore-spoken-questions.png', fullPage: true});
  await request.post(`/api/sessions/${detail.session.id}/stop`);
});
