import { test, expect } from '@playwright/test';
import { selectOption } from './select';

test('workspace dropdown supports keyboard selection, long labels, scrolling and dismissal', async ({page,request}) => {
  const workspaces: {id:string;name:string}[]=[];
  for(let i=0;i<18;i++) workspaces.push(await (await request.post('/api/workspaces',{data:{name:`Dropdown ${String(i).padStart(2,'0')} customer discovery research workspace with a long name`}})).json());
  await page.route('**/api/workspaces',route=>route.fulfill({json:workspaces}));
  await page.goto('/');
  const control=page.getByRole('combobox',{name:'Workspace',exact:true});
  await selectOption(control,workspaces[0].id);
  await control.focus();
  await page.keyboard.press('ArrowDown');
  await expect(page.getByRole('listbox')).toBeVisible();
  await expect(page.getByRole('option',{selected:true})).toHaveAttribute('data-value',workspaces[0].id);
  await page.screenshot({path:'/tmp/explore-dropdown-workspace.png'});
  await page.keyboard.press('Escape');
  await expect(control).toBeFocused();
  await expect(control).toHaveAttribute('data-value',workspaces[0].id);
  await control.press('Enter');
  await page.keyboard.type('Dropdown 17');
  await expect(page.getByRole('option').and(page.locator(`[data-value="${workspaces[17].id}"]`))).toBeFocused();
  await page.keyboard.press('Enter');
  await expect(control).toHaveAttribute('data-value',workspaces[17].id);
  await page.reload();
  await expect(control).toHaveAttribute('data-value',workspaces[17].id);
  await control.click();
  await page.mouse.click(600,500);
  await expect(page.getByRole('listbox')).toHaveCount(0);
  await page.setViewportSize({width:390,height:640});
  await control.click();
  const box=(await page.getByRole('listbox').boundingBox())!;
  expect(box.x).toBeGreaterThanOrEqual(0);
  expect(box.x+box.width).toBeLessThanOrEqual(390);
  expect(box.y+box.height).toBeLessThanOrEqual(640);
  await page.screenshot({path:'/tmp/explore-dropdown-mobile.png'});
  await page.keyboard.press('Escape');
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
});

test('analysis dropdown stays inside its popover and Escape closes one layer at a time',async({page})=>{
  let setting={strategy:'legacy',revision:0};
  await page.route('**/api/settings/analysis',route=>{
    if(route.request().method()==='PATCH') setting={strategy:route.request().postDataJSON().strategy,revision:setting.revision+1};
    return route.fulfill({json:setting});
  });
  await page.goto('/');
  const settings=page.getByRole('button',{name:'Analysis settings',exact:true});
  await settings.click();
  const control=page.getByRole('combobox',{name:'Analysis mode',exact:true});
  await expect(control).toHaveCSS('border-top-width','1px');
  await expect(control).toHaveCSS('justify-content','space-between');
  await control.click();
  await expect(page.getByRole('listbox')).toBeVisible();
  await page.screenshot({path:'/tmp/explore-dropdown-analysis.png'});
  await page.keyboard.press('Escape');
  await expect(page.getByRole('listbox')).toHaveCount(0);
  await expect(control).toBeVisible();
  await expect(control).toBeFocused();
  await selectOption(control,'topics');
  await expect(settings).toContainText('Threads');
  await expect(control).toBeFocused();
  await page.keyboard.press('Escape');
  await expect(settings).toBeFocused();
  await expect(control).toBeHidden();
  await settings.click();
  await control.click();
  await page.setViewportSize({width:800,height:700});
  await expect(page.getByRole('listbox')).toHaveCount(0);
  await page.locator('.ex-sidebar-new').click();
  await expect(page.getByRole('dialog')).toBeVisible();
});

test('role dropdown does not submit the participant form and stays disabled while saving',async({page,request})=>{
  const workspace=await (await request.post('/api/workspaces',{data:{name:'Dropdown participant form'}})).json();
  const draft=await (await request.post(`/api/workspaces/${workspace.id}/meetings`,{data:{title:'Participant dropdown test'}})).json();
  const roster=await (await request.get(`/api/meetings/${draft.meeting.id}/participants`)).json();
  await request.put(`/api/meetings/${draft.meeting.id}/participants`,{data:{revision:roster.revision,participants:[{speaker_id:'test-founder',name:'Alex Test',job_role:'Founder',interview_role:'interviewer'}]}});
  let saves=0;
  let release!:()=>void;
  const gate=new Promise<void>(resolve=>{release=resolve;});
  await page.route(`**/api/meetings/${draft.meeting.id}/participants`,async route=>{
    if(route.request().method()!=='PUT') return route.continue();
    saves++;await gate;await route.continue();
  });
  await page.goto('/');
  await selectOption(page.getByRole('combobox',{name:'Workspace',exact:true}),workspace.id);
  const role=page.getByRole('combobox',{name:'Interview role',exact:true});
  await selectOption(role,'customer');
  expect(saves).toBe(0);
  await page.getByRole('button',{name:'Save participants',exact:true}).click();
  await expect(role).toBeDisabled();
  release();
  await expect(page.locator('.ex-participants').getByRole('status')).toHaveText('Participants saved');
  await expect(role).toBeEnabled();
  expect(saves).toBe(1);
  await page.reload();
  await expect(role).toHaveAttribute('data-value','customer');
  await role.click();
  await page.screenshot({path:'/tmp/explore-dropdown-participants.png'});
});
