import { test, expect } from "@playwright/test";
import { startTest } from "./prepared";
import { selectOption } from "./select";

test("manual analysis keeps capture separate and updates coverage only after a click", async ({page,request}) => {
  const title = `Manual review ${Date.now()}`;
  const prefs = await (await request.get('/api/settings/analysis')).json();
  await request.patch('/api/settings/analysis', {data:{strategy:'legacy',revision:prefs.revision}});
  const draft = await (await request.post('/api/workspaces/default/meetings', {data:{title}})).json();
  const mid = draft.meeting.id;
  const detail = await startTest(request, mid, false);
  const sid = detail.session.id;
  await page.goto('/');
  await page.getByRole('button', {name:title,exact:true}).click();
  const scheduling = page.getByRole('combobox', {name:'Analysis scheduling'});
  await expect(scheduling).toHaveAttribute('data-value','manual');
  const analyze = page.getByRole('button',{name:'Analyze now',exact:true});
  await expect(analyze).toBeDisabled();
  await request.post(`/api/sessions/${sid}/inject`, {data:{event_id:'manual-one',segment_id:'manual-one',revision:0,speaker_id:'customer',speaker_name:'Sam Test',start_ms:0,end_ms:4000,text:'Last Friday I exported numbers from three ad platforms, pasted them into a spreadsheet and checked each total.',is_final:true}});
  await expect(analyze).toBeEnabled();
  expect((await (await request.get(`/api/sessions/${sid}/experiment`)).json()).calls).toBe(0);
  await analyze.click();
  await expect(page.getByRole('region',{name:'Meeting analysis'})).toContainText('1/1 segments analyzed');
  await expect(analyze).toBeDisabled();
  expect((await (await request.get(`/api/sessions/${sid}/experiment`)).json()).calls).toBe(1);
  await selectOption(scheduling, 'automatic');
  await expect(analyze).toHaveCount(0);
  await selectOption(scheduling, 'manual');
  await expect(analyze).toBeDisabled();
  await request.post(`/api/sessions/${sid}/inject`, {data:{event_id:'manual-two',segment_id:'manual-two',revision:0,speaker_id:'customer',speaker_name:'Sam Test',start_ms:5000,end_ms:8000,text:'We spend two hours reconciling those totals every Friday.',is_final:true}});
  await expect(page.getByText('New speech has not been analyzed. It may already answer a suggested question.')).toBeVisible();
  expect((await (await request.get(`/api/sessions/${sid}/experiment`)).json()).calls).toBe(1);
  await page.setViewportSize({width:390,height:844});
  await expect(scheduling).toBeVisible();
  const layout = await page.locator('.ex-analysis-controls').evaluate(el => ({width:el.getBoundingClientRect().width,scroll:el.scrollWidth}));
  expect(layout.scroll).toBeLessThanOrEqual(Math.ceil(layout.width));
  await page.screenshot({path:'/tmp/explore-manual-mobile.png',fullPage:true});
  await page.setViewportSize({width:1440,height:1000});
  await page.screenshot({path:'/tmp/explore-manual-desktop.png',fullPage:true});
  await page.getByRole('button',{name:'End interview',exact:true}).click();
  await expect(page.getByText('Stopped',{exact:true})).toBeVisible();
  expect((await (await request.get(`/api/sessions/${sid}/experiment`)).json()).calls).toBe(1);
});
