import { selectOption } from "./select";
import { test, expect } from '@playwright/test';
import { startTest } from './prepared';

test('sidebar groups actions, preserves live archive guards and stays usable with a long list', async ({page,request}) => {
  const workspace = await (await request.post('/api/workspaces', {data:{name:'Sidebar layout test'}})).json();
  const meetings = [];
  for (let i=0;i<18;i++) meetings.push((await (await request.post(`/api/workspaces/${workspace.id}/meetings`, {data:{title:`Customer operations discovery with a very long title ${i+1}`}})).json()).meeting);
  await page.goto('/');
  await selectOption(page.getByLabel('Workspace',{exact:true}), workspace.id);
  const nav = page.getByRole('navigation',{name:'Meetings',exact:true});
  await expect(nav.getByRole('button')).toHaveCount(18);
  const first = nav.getByRole('button').first();
  await first.click();
  await expect(first).toHaveAttribute('aria-current','page');
  await page.reload();
  await expect(first).toHaveAttribute('aria-current','page');
  await expect(first.locator('time')).toHaveAttribute('datetime', /\d{4}-/);
  await page.getByRole('searchbox',{name:'Search meetings'}).fill('unmatched');
  await expect(page.getByText('No matching meetings.')).toBeVisible();
  await page.getByRole('searchbox',{name:'Search meetings'}).fill('');
  await page.setViewportSize({width:1440,height:900});
  const inputBox = await page.getByRole('searchbox',{name:'Search meetings'}).boundingBox();
  const iconBox = await page.locator('.ex-sidebar-search svg').boundingBox();
  expect(Math.abs(inputBox!.y + inputBox!.height/2 - iconBox!.y - iconBox!.height/2)).toBeLessThan(2);
  await page.screenshot({path:'/tmp/explore-sidebar-connected.png',fullPage:true});
  await page.setViewportSize({width:1024,height:720});
  expect(await nav.evaluate(el=>el.scrollHeight>el.clientHeight)).toBe(true);
  const tools = page.getByRole('region',{name:'App tools'});
  expect((await tools.boundingBox())!.y+(await tools.boundingBox())!.height).toBeLessThanOrEqual(720);
  await page.getByRole('button',{name:'Workspace actions',exact:true}).click();
  await page.keyboard.press('Escape');
  await expect(page.getByRole('button',{name:'Workspace actions',exact:true})).toBeFocused();
  await page.getByRole('button',{name:'Workspace actions',exact:true}).click();
  await page.getByRole('button',{name:'Archive all meetings',exact:true}).click();
  await expect(page.getByRole('button',{name:'Cancel',exact:true})).toBeFocused();
  await page.keyboard.press('Escape');
  const started = await startTest(request, meetings[0].id);
  await page.getByRole('button',{name:'Workspace actions',exact:true}).click();
  await page.getByRole('button',{name:'Archive all meetings',exact:true}).click();
  await page.getByRole('button',{name:'Archive meetings',exact:true}).click();
  await expect(page.getByRole('dialog').getByRole('alert')).toBeVisible();
  expect((await (await request.get(`/api/workspaces/${workspace.id}/meetings`)).json()).every((m:{archived:number})=>!m.archived)).toBe(true);
  await page.keyboard.press('Escape');
  await request.post(`/api/sessions/${started.session.id}/stop`);
  await page.setViewportSize({width:390,height:844});
  await page.getByRole('button',{name:'Analysis settings',exact:true}).click();
  await expect(page.getByLabel('Analysis mode', {exact:true})).toBeVisible();
  const panel = page.locator('.ex-sidebar-popover:popover-open');
  const bounds=await panel.boundingBox();
  expect(bounds!.x).toBeGreaterThanOrEqual(0);expect(bounds!.x+bounds!.width).toBeLessThanOrEqual(390);
  await page.screenshot({path:'/tmp/explore-sidebar-connected-mobile.png',fullPage:true});
  await page.keyboard.press('Escape');
  await expect(page.getByRole('button',{name:'Analysis settings',exact:true})).toBeFocused();
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
});

test('analysis offline state is visible from the compact control and can recover',async({page})=>{
  let offline=true;
  await page.route('**/api/settings/analysis',route=>route.fulfill(offline?{status:503,json:{message:'Unavailable'}}:{json:{strategy:'topics',revision:1}}));
  await page.goto('/');
  const trigger=page.getByRole('button',{name:'Analysis settings',exact:true});
  await expect(trigger).toContainText('Offline');
  await trigger.click();
  await expect(page.getByLabel('Analysis mode', {exact:true})).toBeDisabled();
  await expect(page.getByRole('region',{name:'Analysis settings'}).getByRole('alert')).toContainText('unavailable');
  offline=false;await page.getByRole('button',{name:'Refresh setting'}).click();
  await expect(page.getByLabel('Analysis mode', {exact:true})).toBeEnabled();
  await expect(trigger).toContainText('Threads');
});
